In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [8]:
A = np.random.randn(10)

A

array([-1.71663141, -0.20387969, -0.16243897,  0.86677484, -0.4367116 ,
       -0.76473124, -0.35177751,  1.58650457,  0.90658199, -1.18697572])

In [9]:
B = np.random.randn(10)
B

array([ 0.85527766, -0.31622552,  1.24421008, -0.59720644, -1.52979226,
       -0.02252064, -0.42249862,  0.84038606, -0.07917929, -1.15826508])

In [10]:
np.add(A,B)

array([-0.86135375, -0.52010521,  1.08177111,  0.2695684 , -1.96650386,
       -0.78725188, -0.77427612,  2.42689063,  0.8274027 , -2.3452408 ])

In [11]:
np.maximum(A,B)

array([ 0.85527766, -0.20387969,  1.24421008,  0.86677484, -0.4367116 ,
       -0.02252064, -0.35177751,  1.58650457,  0.90658199, -1.15826508])

In [12]:
np.minimum(A,B)

array([-1.71663141, -0.31622552, -0.16243897, -0.59720644, -1.52979226,
       -0.76473124, -0.42249862,  0.84038606, -0.07917929, -1.18697572])

In [13]:
website = 'https://www.google.com'
import webbrowser
webbrowser.open(website)

True