In [1]:
import numpy as np

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
np.save('myarray',arr)

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [7]:
arr1 = np.load('myarray.npy')

In [8]:
arr2 = arr

In [9]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.savez('ziparray.npz',x=arr1,y=arr2)

In [13]:
archieve_array = np.load('ziparray.npz')

In [15]:
archieve_array['x']

array([0, 1, 2, 3, 4])

In [18]:
archieve_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.savetxt('mytextarray.txt',arr,delimiter=",")

In [25]:
arr = np.loadtxt('mytextarray.txt',delimiter=",")
arr

array([[1., 2., 3.],
       [4., 5., 6.]])